[fugitivedust]

## production table identifier (feedstock_measure in production data)
onfarm_feedstock_measure_type = 'harvested'
onroad_feedstock_measure_type = 'production'

## particulate matter emission factors by acreage
fugitive_dust_factors = 'data/inputs/fugitive_dust_emission_factors.csv'

## road silt content by state
silt_content = 'data/inputs/fugitive_dust_silt_content.csv'

## constants for calculating onroad fugitive dust
fugitive_dust_onroad_constants = 'data/inputs/fugitive_dust_onroad_constants.csv'
