[run_config]
## run identifier
scenario_name = 'test'

## project output directory
project_path = '/Users/dhetting/src/fpeam/prj_path'

## modules to run
modules = 'emissionfactors'

## logging verbosity level (CRITICAL, ERROR, WARNING, INFO, DEBUG, UNSET)
logger_level = DEBUG

## use the router engine to calculate vmt by county
use_router_engine = True

## data paths
equipment = 'data/equipment/bts16_equipment.csv'
production = 'data/production/production_2017_bc1060.csv'
feedstock_loss_factors = 'data/inputs/feedstock_loss_factors.csv'

## forest feedstocks have different allocation indicators in NONROAD and onroad fugitive dust calculations
forestry_feedstock_names = 'forest whole tree', 'forest residues'

## MOVES routing graph
transportation_graph = 'data/inputs/transportation_graph.csv'

## if router is not used, assume 20 vehicle miles traveled per biomass production county
vmt_short_haul = 20

## truck capacities for feedstock transportation
truck_capacity = 'data/inputs/truck_capacity.csv'

## graph node locations
node_locations = 'data/inputs/node_locations.csv'

## data backfill flag
backfill = True
